title: Helm Charts

remote_theme: jekyll/minima

header_pages:
  - README.md

titles_from_headings:
  strip_title: true

minima:
  skin: auto
  social_links:
    - platform: github
      user_url: https://github.com/gabe565/charts
