{{- $sName := "" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: "{{ .Release.Name }}-env-config"
  annotations:
    {{- with .Values.server.config.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: "{{ .Release.Name }}-config"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "{{ .Release.Name }}-config"
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- with .Values.server.config.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  PUID: "{{ .Values.server.config.puid }}"
  PGID: "{{ .Values.server.config.pgid }}"
  PORT: "{{ .Values.server.config.port }}"
  PLAYERS: "{{ .Values.server.config.max_players }}"
  MULTITHREADING: "{{ .Values.server.config.multithreading }}"
  {{ if .Values.server.config.rcon.enable }}
  RCON_ENABLED: "true"
  RCON_PORT: "{{ .Values.server.config.rcon.port }}"
  {{ end }}
  {{ if .Values.server.config.community.enable }}
  COMMUNITY: "true"
  {{ end }}
  {{ if .Values.server.config.server_name }}
  SERVER_NAME: {{ regexReplaceAll "\\W+" .Values.server.config.server_name "_" }}
  {{ else }}
  SERVER_NAME: {{ printf "%s_%s" "palworld" (randAlphaNum 6 | nospace) }}
  {{ end }}
  TZ: {{ .Values.server.config.timezone }}
  PUBLIC_IP: {{ .Values.server.config.public_ip | quote }}
  PUBLIC_PORT: {{ .Values.server.config.public_port | quote }}
  SERVER_DESCRIPTION: {{ .Values.server.config.server_description }}
  QUERY_PORT: {{ .Values.server.config.query_port | quote }}
  {{ if .Values.server.config.env }}
  {{- with .Values.server.config.env }}
  {{- toYaml . | nindent 2  }}
  {{- end }}
  {{- end }}
