{{ if .Values.server.config.daily_reboot.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: "{{ .Values.server.config.daily_reboot.role }}"
    namespace: {{ .Release.Namespace }}
rules:
  {{- if .Values.server.config.rcon.enable }}
    - apiGroups: ["apps", "extensions"]
      resources: ["deployments", "pods"]
      verbs: ["get", "patch", "list", "watch"]
    - apiGroups:  [""]
      resources:  ["pods/exec", "pods"]
      verbs:  ["get", "list", "create"]
  {{- else }}
    - apiGroups: ["apps"]
      resources: ["deployments"]
      resourceNames: ["{{ .Release.Name }}-server"]
      verbs: ["get", "patch"]
  {{- end }}
{{ end }}
